<a href="https://colab.research.google.com/github/saranyaece30111998-analyst/numpy-fundamentals/blob/main/data_transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## data transformation using numpy

In [ ]:
#  reading an Excel file directly from Google Drive in Google Colab:
# Import Google Drive module
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Import pandas
import pandas as pd

# Give Excel file path from Google Drive
# Replace file name/path with your actual file
file_path ='/content/drive/MyDrive/Employee_data.csv'



# Read Excel file
df = pd.read_csv(file_path)
df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car,Useless_Col
0,1000,hannah,NaN,finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0,NaN
1,1001,ivan,30.0,it,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0,remove_me
2,1002,frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1,remove_me
3,1003,david,NaN,IT,Data-Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN,remove_me
4,1004,mike,28.0,finanace,$Developer$,16-Aug-19,60000,NaN,NaN,1,remove_me
...,...,...,...,...,...,...,...,...,...,...,...
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1,NaN
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0,remove_me
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1,remove_me
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0,NaN
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No,remove_me

In [ ]:
df

RecursionError: maximum recursion depth exceeded

RecursionError: maximum recursion depth exceeded

# Data Inspection
# Data inspection is the first step after loading a dataset. It helps you understand the structure, quality, and basic statistics of the data.

In [ ]:
# Show first 5 rows of dataset (quick overview of data)
print("First 5 rows:")
print(df.head())

First 5 rows:
   Employee_ID      Name   Age Department        Position  Joining_Date  \
0         1000   hannah    NaN    finance     $Developer$  Sep 16, 2023
1         1001     ivan   30.0         it      Sr@Analyst     29-Aug-22
2         1002    frank   32.0         IT         Intern*    19-04-2023
3         1003    david    NaN         IT  Data-Scientist      02/14/23
4         1004     mike   28.0   finanace     $Developer$     16-Aug-19

   Salary   Feedback   Last_Login_Time Has_Car Useless_Col
0     70k       poor  11-11-2025 22:00       0         NaN
1  45,500  excellent  07-11-2025 05:00       0   remove_me
2     70k       good               NaN       1   remove_me
3   40000       poor  31-10-2025 19:00     NaN   remove_me
4   60000        NaN               NaN       1   remove_me

In [ ]:
# Show last 5 rows of dataset (check ending records)
print("Last 5 rows:")
print(df.tail())

Last 5 rows:
     Employee_ID     Name   Age Department     Position  Joining_Date  Salary  \
200         1095    tina   35.0         HR      Intern*    07-02-2022   60000
201         1015   grace   32.0    FINANCE  $Developer$  Nov 14, 2021     NaN
202         1030    STEVE  32.0         HR  $Developer$    04-03-2018  65,000
203         1158   kevin   24.0         it      Intern*     16-May-23   40000
204         1128   david   30.0         IT  $Developer$    06-02-2023  45,500

    Feedback   Last_Login_Time Has_Car Useless_Col
200      NaN  07-11-2025 04:00       1         NaN
201  average  07-11-2025 20:00       0   remove_me
202     good  04-11-2025 16:00       1   remove_me
203      NaN  10-11-2025 21:00       0         NaN
204      NaN  07-11-2025 21:00      No   remove_me

In [ ]:
# Show random 5 rows (useful for checking randomness in data)
print("Random sample rows:")
print(df.sample(5))

Random sample rows:
     Employee_ID     Name   Age Department     Position Joining_Date  Salary  \
137         1137    tina   24.0      SALES      Intern*     08/28/19   55000
141         1141    OSCAR  24.0    finance  $Developer$   16-12-2019   60000
39          1039     TINA  28.0  marketing     @Manager   08-10-2018  45,500
175         1175   grace   35.0         it     @Manager    01-Feb-23   60000
112         1112   grace   90.0  marketing     #Analyst     08/19/20   60000

    Feedback   Last_Login_Time Has_Car Useless_Col
137        ?  31-10-2025 21:00       1   remove_me
141     good  01-11-2025 03:00       0         NaN
39       NaN  11-11-2025 06:00       1   remove_me
175      NaN  11-11-2025 08:00       0         NaN
112      NaN  03-11-2025 10:00       0   remove_me

In [ ]:
# Show shape of dataset (rows, columns)
print("Shape of dataset (rows, columns):")
print(df.shape)

Shape of dataset (rows, columns):
(205, 11)

In [ ]:
# Show column names in dataset
print("Column names:")
print(df.columns)

Column names:
Index(['Employee_ID', 'Name', 'Age', 'Department', 'Position', 'Joining_Date',
       'Salary', 'Feedback', 'Last_Login_Time', 'Has_Car', 'Useless_Col'],
      dtype='object')

In [ ]:
# Show detailed info (data types, null values, memory usage)
print("Dataset info:")
df.info()

Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Employee_ID      205 non-null    int64
 1   Name             205 non-null    object
 2   Age              174 non-null    float64
 3   Department       205 non-null    object
 4   Position         205 non-null    object
 5   Joining_Date     205 non-null    object
 6   Salary           188 non-null    object
 7   Feedback         142 non-null    object
 8   Last_Login_Time  150 non-null    object
 9   Has_Car          186 non-null    object
 10  Useless_Col      112 non-null    object
dtypes: float64(1), int64(1), object(9)
memory usage: 17.7+ KB

In [ ]:
# Check missing values in each column
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Employee_ID         0
Name                0
Age                31
Department          0
Position            0
Joining_Date        0
Salary             17
Feedback           63
Last_Login_Time    55
Has_Car            19
Useless_Col        93
dtype: int64

In [ ]:
# Check duplicate rows in dataset
print("Number of duplicate rows:")
print(df.duplicated().sum())

Number of duplicate rows:
5

In [ ]:
# Show data types of each column
print("Data types of columns:")
print(df.dtypes)

Data types of columns:
Employee_ID          int64
Name                object
Age                float64
Department          object
Position            object
Joining_Date        object
Salary              object
Feedback            object
Last_Login_Time     object
Has_Car             object
Useless_Col         object
dtype: object

In [ ]:
# Show summary statistics for numeric columns
# Includes count, mean, std, min, 25%, 50%, 75%, max
print("Statistical summary:")
print(df.describe())

Statistical summary:
       Employee_ID         Age
count   205.000000  174.000000
mean   1099.151220   37.528736
std      57.855902   21.307460
min    1000.000000   24.000000
25%    1049.000000   26.000000
50%    1099.000000   30.000000
75%    1149.000000   35.000000
max    1199.000000   90.000000

# **Data Cleaning**

In [ ]:
#drop a single column
df.drop('Useless_Col', axis=1, inplace=True)

In [ ]:
#drop a row (by index)
df.drop(204, axis=0, inplace=True)

# 2.Data quality checks

1.Duplication Removal

In [ ]:
# Returns the total number of duplicated rows
df.duplicated().sum()

np.int64(5)

In [ ]:
#Display Duplicate Rows
df[df.duplicated()]

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No

In [ ]:
#Display All Occurrences of Duplicates

df[df.duplicated(keep=False)]

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
15,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0
30,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1
95,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1
128,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No
158,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No

In [ ]:
# Remove duplicates
df.drop_duplicates(inplace=True)

# name column cleaning

In [ ]:
df['Name']=df['Name'].str.title().str.strip()

# AGE COLUMN

In [ ]:
df['Age'].fillna(df['Age'].mean,inplace=True)

/tmp/ipykernel_4589/2670672150.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '<bound method Series.mean of 0       NaN
1      30.0
2      32.0
3       NaN
4      28.0
       ...
195    26.0
196    26.0
197    30.0
198    32.0
199    28.0
Name: Age, Length: 200, dtype: float64>' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['Age'].fillna(df['Age'].mean,inplace=True)

DEPARTMENT COLUMN

In [ ]:
# finf unique value in department
df['Department'].unique()

array(['Finance', 'IT', 'HR', 'Sales', 'Marketing'], dtype=object)

In [ ]:
# find value count of department
df['Department'].value_counts()

Department
Finance      61
IT           47
HR           41
Sales        27
Marketing    24
Name: count, dtype: int64

In [ ]:
# upper casing all names
df['Department']=df['Department'].str.upper()

In [ ]:
# replace values
df['Department'].replace('FINANACE','Finance',inplace=True)

/tmp/ipykernel_4589/3464717638.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Department'].replace('FINANACE','Finance',inplace=True)

In [ ]:
# replace multiple values
df['Department'].replace({'FINANCE':'Finance',
                          'MARKETING':'Marketing',
                          'SALES':'Sales'},inplace=True)

/tmp/ipykernel_4589/2248755528.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Department'].replace({'FINANCE':'Finance',

# position column

In [ ]:
df['Position'].unique()

array([' Developer ', 'Sr Analyst', 'Intern ', 'Data Scientist',
       ' Manager', ' Clerk', ' Analyst'], dtype=object)

In [ ]:
# Remove any special characters like !, @, #, etc.
df['Position']=df['Position'].str.replace(r'[^a-zA-Z ]',' ', regex=True)

# salary column

In [ ]:
df['Salary'].unique()

array(['70k', '45,500', '40000', '60000', nan, '65,000', '55000', '50000'],
      dtype=object)

In [ ]:
#DISPLAYING SALARY
df["Salary"].value_counts(dropna = False)

Salary
40000     33
60000     31
45,500    30
55000     27
70k       23
65,000    23
50000     17
NaN       16
Name: count, dtype: int64

In [ ]:
df["Salary"] = df['Salary'].str. replace("70k","70000").str.replace(",","")

In [ ]:
# changeing data types
df["Salary"]= df["Salary"].astype(float)

In [ ]:
# Hierarchical imputation
# Level 1: Department + Position mean
dept_pos_mean = df.groupby(['Department','Position'])['Salary'].transform('median')

# # # # Level 2: Department mean
dept_mean = df.groupby('Department')['Salary'].transform('mean')

# # # Level 3: Overall mean
overall_mean = df['Salary'].mean()

# Hierarchical imputation
df['Salary'] = (df['Salary'].fillna(dept_pos_mean).fillna(dept_mean).fillna(overall_mean))

# Feedback column

In [ ]:
df["Feedback"].unique()

array(['poor', 'excellent', 'good', nan, 'average', '?'], dtype=object)

In [ ]:
df["Feedback"].value_counts()

Feedback
poor         31
good         29
average      29
?            26
excellent    25
Name: count, dtype: int64

In [ ]:
df["Feedback"] = df['Feedback'].str. replace("?","Average").str.title()

In [ ]:
df["Feedback"] = df['Feedback'].fillna("Average")

In [ ]:
df["Has_Car"].unique()

array(['0', '1', nan, 'No', 'Yes'], dtype=object)

In [ ]:
df['Has_Car'].replace({
    '0': 'No',
    '1': 'Yes'
}, inplace=True)

/tmp/ipykernel_4589/1435213368.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Has_Car'].replace({

In [ ]:
df["Has_Car"] = df['Has_Car'].fillna("No")

In [ ]:
df

NameError: name 'df' is not defined