<a href="https://colab.research.google.com/github/saranyaece30111998-analyst/numpy-fundamentals/blob/main/group_by.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
# Create first DataFrame (Employee details)
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5, 6],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Age': [25, 30, 28, 35, 26, 40],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'Marketing', 'Finance'],
    'Salary': [45000, 60000, 52000, 75000, 48000, 82000]
})

# Create second DataFrame (Location details)
df2 = pd.DataFrame({
    'ID': [1, 2, 3, 4, 6, 7],
    'City': ['Delhi', 'Mumbai', 'Bangalore', 'Chennai', 'Hyderabad', 'Pune'],
    'State': ['Delhi', 'Maharashtra', 'Karnataka', 'Tamil Nadu', 'Telangana', 'Maharashtra'],
    'Country': ['India', 'India', 'India', 'India', 'India', 'India']
})
print(df1)
print(df2)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   45000
1   2      Bob   30         IT   60000
2   3  Charlie   28    Finance   52000
3   4    David   35         IT   75000
4   5      Eva   26  Marketing   48000
5   6    Frank   40    Finance   82000
   ID       City        State Country
0   1      Delhi        Delhi   India
1   2     Mumbai  Maharashtra   India
2   3  Bangalore    Karnataka   India
3   4    Chennai   Tamil Nadu   India
4   6  Hyderabad    Telangana   India
5   7       Pune  Maharashtra   India

In [ ]:
df_inner = pd.merge(
    df1[['ID', 'Name', 'Salary']],
    df2[['ID', 'City']],
    on='ID',
    how='inner'
)
df_inner

   ID     Name  Salary       City
0   1    Alice   45000      Delhi
1   2      Bob   60000     Mumbai
2   3  Charlie   52000  Bangalore
3   4    David   75000    Chennai
4   6    Frank   82000  Hyderabad

In [ ]:
df_left = pd.merge(
    df1[['ID', 'Name', 'Salary']],
    df2[['ID', 'City']],
    on='ID',
    how='left'
)
df_left

   ID     Name  Salary       City
0   1    Alice   45000      Delhi
1   2      Bob   60000     Mumbai
2   3  Charlie   52000  Bangalore
3   4    David   75000    Chennai
4   5      Eva   48000        NaN
5   6    Frank   82000  Hyderabad

In [ ]:
df_right = pd.merge(
    df1[['ID', 'Name', 'Salary']],
    df2[['ID', 'City']],
    on='ID',
    how='right'
)
df_right

   ID     Name   Salary       City
0   1    Alice  45000.0      Delhi
1   2      Bob  60000.0     Mumbai
2   3  Charlie  52000.0  Bangalore
3   4    David  75000.0    Chennai
4   6    Frank  82000.0  Hyderabad
5   7      NaN      NaN       Pune

In [ ]:
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'ID': [4, 5, 6],
    'Name': ['David', 'Eva', 'Frank']
})

In [ ]:
#sample data
data = {
    'Region': ['East', 'West', 'East', 'North', 'West', 'East'],
    'Sales': [200, 300, 250, 400, 150, 350],
    'Profit': [20, 30, 25, 40, 15, 35]
}

df =pd.DataFrame(data)

In [ ]:
# Find total sales generated in each region
region_sales=df.groupby("Region")["Profit"].sum()
print(region_sales)

Region
East     80
North    40
West     45
Name: Profit, dtype: int64

In [ ]:
#Calculate average profit for each region
region_average_profit=df.groupby("Region")["Profit"].mean()
print(region_average_profit)

Region
East     26.666667
North    40.000000
West     22.500000
Name: Profit, dtype: float64