<a href="https://colab.research.google.com/github/saranyaece30111998-analyst/numpy-fundamentals/blob/main/pandas_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [7]:
import pandas as pd

# pandas series

In [9]:


s = pd.Series([10, 20, 30, 40])
print(s)
print(type(s))

0    10
1    20
2    30
3    40
dtype: int64
<class 'pandas.core.series.Series'>

In [10]:
# DataFrame: Create from a dictionary: 2D labeled table
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Age': [24, 30, 28, 35, 22, 40],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Berlin', 'Sydney']
}
print(data)

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'], 'Age': [24, 30, 28, 35, 22, 40], 'City': ['New York', 'London', 'Paris', 'Tokyo', 'Berlin', 'Sydney']}

In [13]:
df=pd.DataFrame(data)
(df)

      Name  Age      City
0    Alice   24  New York
1      Bob   30    London
2  Charlie   28     Paris
3    David   35     Tokyo
4      Eva   22    Berlin
5    Frank   40    Sydney

In [14]:
# Creating Dictionary
data = {
    'ID': [101, 102, 103, 104, 105, 106],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Age': [24, 30, 28, 35, 22, 40],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Berlin', 'Sydney'],
    'Salary': [50000, 60000, 55000, 70000, 48000, 75000],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'Marketing', 'Finance']
}

# Convert Dictionary to DataFrame
df = pd.DataFrame(data)

print("Original DataFrame")
print(df)

Original DataFrame
    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance
3  104    David   35     Tokyo   70000         IT
4  105      Eva   22    Berlin   48000  Marketing
5  106    Frank   40    Sydney   75000    Finance

In [21]:
df

    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance
3  104    David   35     Tokyo   70000         IT
4  105      Eva   22    Berlin   48000  Marketing
5  106    Frank   40    Sydney   75000    Finance

In [25]:
## Accesssing columns in pandas DataFrame
df["City"]

0    New York
1      London
2       Paris
3       Tokyo
4      Berlin
5      Sydney
Name: City, dtype: object

In [24]:
# one or Columns using
print(df[["Name","City"]])

      Name      City
0    Alice  New York
1      Bob    London
2  Charlie     Paris
3    David     Tokyo
4      Eva    Berlin
5    Frank    Sydney

In [30]:
df.loc[2]
df.loc[2:4]
df.loc[2,"City"]

'Paris'

In [31]:
print(df.loc[0:3])
print(df.iloc[0:3])

    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance
3  104    David   35     Tokyo   70000         IT
    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance

In [35]:
print(df.loc[2,"Name"])
print(df.iloc[2,1])

Charlie
Charlie

In [39]:
# fittering data
df[df["Age"] > 25]
df_nonIT = df[df["Department"] != "IT"].reset_index(drop=True)
print(df_nonIT)

    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  103  Charlie   28     Paris   55000    Finance
2  105      Eva   22    Berlin   48000  Marketing
3  106    Frank   40    Sydney   75000    Finance

In [47]:
#sorting values
# Upload File from Your Local System
#  Import files module
from google.colab import files

# Upload file from local system
uploaded = files.upload()

# #data frame conversion
df = pd.read_excel("Fitness Tracker.xlsx")
df

Saving Fitness Tracker.xlsx to Fitness Tracker (3).xlsx

,User ID,Date,Workout Type,Workout Duration (Minutes),Calories Burned,Steps Count,Calories Consumed,Sleep Duration (Hours),Sleep Quality,Weight (kg)
0,USR-9001,2024-07-01,Cycling,65,588,2716,1997,9.2,Fair,67.9
1,USR-9001,2024-07-02,Yoga,45,140,4289,2190,7.6,Excellent,67.9
2,USR-9001,2024-07-03,Cycling,38,337,3812,2611,9.4,Excellent,67.9
3,USR-9001,2024-07-04,Running,30,258,10401,2417,7.8,Excellent,67.9
4,USR-9001,2024-07-05,Running,62,678,8579,2801,5.3,Poor,67.9
...,...,...,...,...,...,...,...,...,...,...
995,USR-9050,2024-07-16,Yoga,44,76,4693,1856,4.6,Excellent,56.8
996,USR-9050,2024-07-17,HIIT,39,273,9469,1479,7.5,Good,56.7
997,USR-9050,2024-07-18,Yoga,39,67,8594,1834,7.7,Excellent,56.7
998,USR-9050,2024-07-19,HIIT,30,238,6649,1782,7.4,Fair,56.7
999,USR-9050,2024-07-20,HIIT,36,251,5189,1708,9.2,Excellent,56.7